config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

    resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @newcar = Car.new
  end

  def create
    @car = Car.create car_params
    redirect_to root_path
  end

  def car_params
    params.require(:car).permit(
      :Make,
      :Model,
      :Year,
      :Color
        )
  end

  def show
    @car = Car.find params[:id]
  end

  def edit
    @car = Car.find params[:id]
  end

  def update
    @car = Car.find params[:id]
    @car.update_attributes car_params
    redirect_to root_path
  end

  def destroy
    @car = Car.find params[:id]
    @car.delete
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cars = Car.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/edit.html.erb
<h1>Edit Page</h1>

<%= form_for @car do |f| %>
<%= f.label :Make %>
<%= f.text_field :Make %>
<%= f.label :Model %>
<%= f.text_field :Model %>
<%= f.label :Year %>
<%= f.text_field :Year %>
<%= f.label :Color %>
<%= f.text_field :Color %>
<br>
<%= f.submit %>
<% end %>

app/views/cars/new.html.erb
<%= link_to "Home Page", root_path %>

<%= form_for @newcar do |f| %>
<%= f.label :Make %>
<%= f.text_field :Make %>
<br>
<%= f.label :Model %>
<%= f.text_field :Model %>
<br>
<%= f.label :Year %>
<%= f.text_field :Year %>
<br>
<%= f.label :Color %>
<%= f.text_field :Color %>
<br>
<%= f.submit %>

<% end %>

app/views/cars/show.html.erb
<%= @car.Make %>
<br>
<%= @car.Model %>
<br>
<%= @car.Year %>
<br>
<%= @car.Color %>
<br>

<br>
<%= link_to "Edit", edit_car_path(@car) %>
<br>
<%= link_to "Delete", car_path(@car), method: :delete %>
<br>
<br>
<%= link_to "Home Page", root_path %>

app/views/home/index.html.erb
<%= link_to "Add Car", new_car_path %>

<ul>
<% @cars.each do |car| %>
    <li><%= car.Make %></li>
    <li><%= car.Model %></li>
    <li><%= car.Year %></li>
    <li><%= car.Color %></li>
    <%= link_to "Show", car_path(car) %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day11Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Adam's Super Sweet Car Lot</h1>

<%= yield %>

</body>
</html>